#### Part 1

In [2]:
import numpy as np

##### Notes
- Numpy arrays better optimized to handle vectorized operations
- Cannot change length post creation
- List can have multiplt dtypes, np array has only 1

In [2]:
list1 = [[1,2,3], [2,2,2], [3,3,3]]
arr_2d = np.array(list1)

In [3]:
arr_2d

array([[1, 2, 3],
       [2, 2, 2],
       [3, 3, 3]])

In [4]:
type(arr_2d)

numpy.ndarray

In [5]:
arr_2d.dtype

dtype('int32')

In [6]:
arr_2d_2 = np.array(list1, dtype='float')

In [7]:
arr_2d_2

array([[1., 2., 3.],
       [2., 2., 2.],
       [3., 3., 3.]])

- np.nditer
- fortran order

In [8]:
arr_2d_2.astype('int')

array([[1, 2, 3],
       [2, 2, 2],
       [3, 3, 3]])

In [9]:
np2list = arr_2d.tolist()

In [10]:
np2list

[[1, 2, 3], [2, 2, 2], [3, 3, 3]]

In [11]:
arr_2d.tobytes()

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00'

In [12]:
arr_2d.tostring() #ascii string

<ipython-input-12-092650fd4f4b>:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  arr_2d.tostring() #ascii string


b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00'

##### Dtypes and Shape

In [13]:
arr_2d

array([[1, 2, 3],
       [2, 2, 2],
       [3, 3, 3]])

In [14]:
arr_2d.astype('float')

array([[1., 2., 3.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [15]:
arr_2d.shape

(3, 3)

In [16]:
arr_2d.dtype

dtype('int32')

In [17]:
arr_2d.size

9

In [18]:
len(arr_2d)

3

In [19]:
arr_2d.ndim #number of dimensions

2

In [20]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [21]:
arr1d = np.arange(10, 20, 2)

In [22]:
arr1d

array([10, 12, 14, 16, 18])

In [23]:
arr1d.ndim

1

In [24]:
arr1d * 3

array([30, 36, 42, 48, 54])

In [25]:
arr1d + 5

array([15, 17, 19, 21, 23])

In [26]:
arr1d[0]

10

In [27]:
arr1d[0:2]

array([10, 12])

In [28]:
arr_2d[0][1]

2

In [29]:
boolarr = arr_2d < 3

In [30]:
boolarr

array([[ True,  True, False],
       [ True,  True,  True],
       [False, False, False]])

In [31]:
arr_2d[boolarr]

array([1, 2, 2, 2, 2])

In [32]:
arr_2d

array([[1, 2, 3],
       [2, 2, 2],
       [3, 3, 3]])

In [33]:
arr_2d[::-1, ]

array([[3, 3, 3],
       [2, 2, 2],
       [1, 2, 3]])

In [34]:
arr_2d[::-1, ::-1]

array([[3, 3, 3],
       [2, 2, 2],
       [3, 2, 1]])

##### np.nan, np.inf

In [35]:
np.nan

nan

In [36]:
np.inf

inf

In [37]:
arr_2d

array([[1, 2, 3],
       [2, 2, 2],
       [3, 3, 3]])

In [38]:
arr_2d = arr_2d.astype('float')

In [39]:
arr_2d

array([[1., 2., 3.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [40]:
arr_2d[0][0] = np.nan
arr_2d[0][1] = np.inf

In [41]:
arr_2d

array([[nan, inf,  3.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

np.nan is a float in the background

In [42]:
np.isnan(arr_2d)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [43]:
np.isinf(arr_2d)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [44]:
missing_flag = np.isnan(arr_2d) | np.isinf(arr_2d)

In [45]:
missing_flag

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [46]:
#replace nan and inf wit 0
arr_2d[np.isnan(arr_2d) | np.isinf(arr_2d)] = 0

In [47]:
arr_2d

array([[0., 0., 3.],
       [2., 2., 2.],
       [3., 3., 3.]])

##### Statistical Methods

In [48]:
arr_2d.min()

0.0

In [49]:
arr_2d.max()

3.0

In [50]:
arr_2d.mean()

2.0

In [51]:
arr_2d.std()

1.1547005383792515

In [52]:
arr_2d.var()

1.3333333333333333

In [53]:
arr_2d.var(axis=1) #compute along cols

array([2., 0., 0.])

In [54]:
arr_2d.var(axis=0) #compute along rows

array([1.55555556, 1.55555556, 0.22222222])

In [55]:
arr_2d

array([[0., 0., 3.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [56]:
arr_2d.shape

(3, 3)

In [57]:
tst_arr = np.array([[[1], [2], [3]]])

In [58]:
tst_arr

array([[[1],
        [2],
        [3]]])

In [59]:
tst_arr.shape 
#every squared bracket lets u enter an entity and counting 
#the elements of each entity gives the shape... 
#counting the number of sq brackets gives dimensions

(1, 3, 1)

In [60]:
tst_arr.ndim

3

In [61]:
tst2 = tst_arr.squeeze()

In [62]:
tst2

array([1, 2, 3])

In [63]:
tst2.shape

(3,)

In [64]:
tst2.cumsum()

array([1, 3, 6], dtype=int32)

In [65]:
tst2.cumprod()

array([1, 2, 6], dtype=int32)

In [66]:
arr_2d

array([[0., 0., 3.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [67]:
arr_2d[:2:,:2:]

array([[0., 0.],
       [2., 2.]])

In [68]:
arr_2d[:2,:2]

array([[0., 0.],
       [2., 2.]])

In [69]:
arr_2d[1:,1:]

array([[2., 2.],
       [3., 3.]])

In [70]:
arr_2d[1:,2:]

array([[2.],
       [3.]])

In [71]:
arr_2d.reshape(1,9)

array([[0., 0., 3., 2., 2., 2., 3., 3., 3.]])

In [72]:
arr_2d.flatten() 
#notice since we passed 2 args in the reshape method, it gives a 2d matrix/array
#flatten produces a 1D array

array([0., 0., 3., 2., 2., 2., 3., 3., 3.])

In [73]:
arr_2d.ravel() 
#ravel references to the parent array, hence any changes made 
#to a raveled array will affect the parent array too

array([0., 0., 3., 2., 2., 2., 3., 3., 3.])

In [74]:
a = arr_2d.flatten() #copy
b = arr_2d.ravel() #reference

In [75]:
a[0] = 123

In [76]:
a

array([123.,   0.,   3.,   2.,   2.,   2.,   3.,   3.,   3.])

In [77]:
arr_2d

array([[0., 0., 3.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [78]:
b[0:3] = 2134

In [79]:
b

array([2.134e+03, 2.134e+03, 2.134e+03, 2.000e+00, 2.000e+00, 2.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00])

In [80]:
arr_2d

array([[2.134e+03, 2.134e+03, 2.134e+03],
       [2.000e+00, 2.000e+00, 2.000e+00],
       [3.000e+00, 3.000e+00, 3.000e+00]])

##### Sequence, Repetitions & Random Numbers

In [81]:
np.arange(1, 10, dtype='int')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.arange(2, 50, 2, dtype='int')

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [83]:
np.arange(1, 50, 2, dtype='int')

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [84]:
np.linspace(1, 50, 30)

array([ 1.        ,  2.68965517,  4.37931034,  6.06896552,  7.75862069,
        9.44827586, 11.13793103, 12.82758621, 14.51724138, 16.20689655,
       17.89655172, 19.5862069 , 21.27586207, 22.96551724, 24.65517241,
       26.34482759, 28.03448276, 29.72413793, 31.4137931 , 33.10344828,
       34.79310345, 36.48275862, 38.17241379, 39.86206897, 41.55172414,
       43.24137931, 44.93103448, 46.62068966, 48.31034483, 50.        ])

In [85]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [86]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [87]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [88]:
np.zeros_like(arr_2d)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
#fortran order - column-major ordering

In [90]:
a = [1,2,3]

In [91]:
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [92]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [93]:
np.repeat(arr_2d, 3)

array([2.134e+03, 2.134e+03, 2.134e+03, 2.134e+03, 2.134e+03, 2.134e+03,
       2.134e+03, 2.134e+03, 2.134e+03, 2.000e+00, 2.000e+00, 2.000e+00,
       2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00, 2.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00, 3.000e+00,
       3.000e+00, 3.000e+00, 3.000e+00])

In [94]:
np.random.rand(3,4)

array([[0.68051081, 0.75241602, 0.75531913, 0.58313291],
       [0.73455833, 0.20806685, 0.90111316, 0.83789638],
       [0.79226861, 0.75820141, 0.54342185, 0.5002574 ]])

In [95]:
np.random.randn(5,3)

array([[ 1.33610492, -0.39948781, -0.54430419],
       [ 0.59216583, -0.43596749, -1.61812083],
       [-0.7462591 , -3.3672428 ,  0.47444445],
       [-1.31866341,  1.09479426,  1.09329898],
       [ 0.21724336,  0.39217758,  0.97972092]])

In [96]:
np.random.randint(0,10, [5,3])

array([[2, 9, 9],
       [9, 2, 6],
       [6, 8, 2],
       [3, 9, 9],
       [8, 0, 2]])

In [97]:
np.random.seed(0) #seed will help get the same random numbers always
np.random.randint(0,10, [5,3])

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [98]:
arr_2d

array([[2.134e+03, 2.134e+03, 2.134e+03],
       [2.000e+00, 2.000e+00, 2.000e+00],
       [3.000e+00, 3.000e+00, 3.000e+00]])

In [99]:
np.unique(arr_2d)

array([2.000e+00, 3.000e+00, 2.134e+03])

In [100]:
np.unique(arr_2d, return_counts=True)

(array([2.000e+00, 3.000e+00, 2.134e+03]), array([3, 3, 3], dtype=int64))

In [101]:
uniques, counts = np.unique(arr_2d, return_counts=True)

In [102]:
uniques

array([2.000e+00, 3.000e+00, 2.134e+03])

In [103]:
counts

array([3, 3, 3], dtype=int64)

#### Part 2

In [3]:
arr = np.random.randint(2, 100, [5,3])

In [4]:
arr

array([[68, 62,  7],
       [28, 72, 39],
       [51, 98, 15],
       [45, 82, 67],
       [67, 48, 60]])

In [5]:
np.where(arr>70)

(array([1, 2, 3], dtype=int64), array([1, 1, 1], dtype=int64))

In [8]:
arr[np.where(arr>55)]

array([68, 62, 72, 98, 82, 67, 67, 60])

In [9]:
arr[arr>55]

array([68, 62, 72, 98, 82, 67, 67, 60])

In [10]:
np.where(arr>55, 'gt55', 'lt55')

array([['gt55', 'gt55', 'lt55'],
       ['lt55', 'gt55', 'lt55'],
       ['lt55', 'gt55', 'lt55'],
       ['lt55', 'gt55', 'gt55'],
       ['gt55', 'lt55', 'gt55']], dtype='<U4')

In [11]:
arr.max()

98

In [12]:
arr.argmax()

7

In [13]:
arr

array([[68, 62,  7],
       [28, 72, 39],
       [51, 98, 15],
       [45, 82, 67],
       [67, 48, 60]])

In [14]:
# min, argmin

In [17]:
arr.argmin()

2

In [18]:
arr.min()

7

In [22]:
# np.genfromtxt(file, delimiter=, skip_header=, filling_values=, dtype=)
# dtype can be 'object' or None if dataset has both numbers and strings
# np.set_printoptions(suppress=True) - turns off scientific notation for numbers

In [ ]:
# np.savetxt('filename.csv', data, delimiter=)
# np.save('filename.npy', data)... savez for multiple arrays, here format is npz
# np.load to load npy or npz format files
# after loading npz file, using the .files() method we can see a list of arrays in the npz file
# 